### ISSUE TITLE
Re/Connecting while in Chat

### ISSUE THREAD

**Issue by D0nDiscord** [kisuka/YiffSpot#22]
While using the website, i always seem to have the Problem of constant Connection loss, and with that, loosing the Chatpartner. Stable Internetconnection on my Side.

**Comment by kisuka** [comment]
Yeah I've been trying to figure that issue out for awhile now. Might have something to do with nginx killing the session too soon. At the moment it does a pass through nginx, but I guess I could switch it to express fully and see how it performs. I was going to implement a way to auto-reconnect back to your previous partner but due to not saving the session ID in browser and keeping people anonymous, it's a bit hard to do that sadly.

**Comment by curiousgeek123** [comment]
@kisuka  i am facing the same issue, did you find any way to add reconnection logic in this?
Also, when are you going to fully dockerize the project, because i am having some errors when running NPM INSTALL, please see below. can u help me suggest what am i doing wrong while running the project locally?

![image](https://user-images.githubusercontent.com/61917543/76161000-e9710e80-6150-11ea-94a0-f063b5f2904d.png)
